import NavBar from "@components/NavBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@components/Footer";

const inter = Inter({
  weight: ["400"],
  subsets: ["latin", "cyrillic"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  //   applicationName:
  //   openGraph: {
  //     title,
  //     description,
  //     images: [
  //         {url:"image",
  //             width: 800,
  //             height:600,
  //             alt:"description"
  //         }
  //     ],
  //     type: "website"
  //   }
  //   twitter,
  //   icons
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body className={inter.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
